// Page ids used by the site before the v0.6 regrouping, and where each page moved.
// Generated once from the edition 1.1 manifest and the table in Appendix M5, section M5.3.
export const MOVED_PAGES: Record<string, string> = {
  'app-a-method': 'app-m1-method',
  'app-b-corrections': 'app-m5-changelog',
  'app-c-feedstocks': 'app-s4-feedstocks',
  'app-d-retail-audit': 'app-s2-retail-audit',
  'app-e-directory': 'app-s1-directory',
  'app-f-facilities': 'app-s5-facilities',
  'app-g-regulation': 'app-s9-regulation',
  'app-h-feed-market': 'app-s6-feed-market',
  'app-i-costs': 'app-s12-costs',
  'app-j-science': 'app-s13-science',
  'app-k-research': 'app-s7-research',
  'app-l-labs-talent': 'app-s8-labs-talent',
  'app-m-capital': 'app-s11-capital',
  'app-n-regional': 'app-s3-regional',
  'app-o-outlook': 'app-f1-outlook',
  'app-p-admin-map': 'app-s10-admin-map',
  'app-q-open-questions': 'app-r1-open-questions',
  'app-r-disagreements': 'app-r2-disagreements',
  'app-s-glossary': 'app-r3-glossary',
  'app-t-sources': 'app-r4-sources',
  'app-u-futures-method': 'app-m2-futures-method',
  'app-v-frontier-tech': 'app-f3-frontier-tech',
  'app-w-balance-model': 'app-f4-balance-model',
  'app-x-drivers-signals': 'app-f2-drivers-signals',
  'app-y-targets-hubs': 'app-f5-targets-hubs',
  'app-z-aquafeed-feedstock-futures': 'app-f6-aquafeed-feedstock-futures',
  'ch02-asset-map': 'ch04-asset-map',
  'ch03-industrial-base': 'ch05-industrial-base',
  'ch04-alt-protein-today': 'ch02-alt-protein-today',
  'ch05-rules': 'ch07-rules',
  'ch07-capital': 'ch08-capital',
  'ch08-regional': 'ch03-regional',
  'ch11-plays': 'ch26-plays',
  'ch12-policy-options': 'ch27-policy-options',
  'ch13-outlook': 'ch19-outlook-2035',
  'ch14-unknowns': 'ch30-unknowns',
  'ch15-drivers-2050': 'ch20-drivers-2050',
  'ch16-frontier-technology': 'ch21-frontier-technology',
  'ch17-protein-balance-2050': 'ch22-protein-balance-2050',
  'ch18-scenarios-2050': 'ch23-scenarios-2050',
  'ch19-vision-2050': 'ch24-vision-2050',
  'ch20-robust-moves': 'ch28-robust-moves',
};
