/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 99b5db26f959ae79deea075a7b429273)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface ProductionEnv {
		MEDIA: R2Bucket;
		DB: D1Database;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
