/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 35a585a3350555bfbe461ae9e96dd768)
interface __BaseEnv_Env {
	SESSION?: KVNamespace;
	MEDIA: R2Bucket;
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface ProductionEnv {
		SESSION: KVNamespace;
		MEDIA: R2Bucket;
		DB: D1Database;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
