"""Write the W8-L2 actor register, standards timeline and T2 price-per-performance tables."""
import csv, os
D = os.path.dirname(os.path.abspath(__file__))
def write(name, rows):
    with open(os.path.join(D, name), 'w', newline='', encoding='utf-8') as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows(rows)
    s = open(os.path.join(D, name), encoding='utf-8').read()
    assert chr(0x2013) not in s and chr(0x2014) not in s, name

reg = [
 dict(actor_id='FBA-A01', actor='Skretting Vietnam (Nutreco)', actor_type='aquafeed mill, multinational',
  vietnam_presence='Thuan Dao branch, Tay Ninh (former Long An); shrimp, pangasius, tilapia, marine fish and trout feed',
  asc_status_sep_2026='Certified 2 Jul 2025 (v1.2)',
  stated_ingredient_strategy='Nutreco RoadMap 2025 target of 5 to 10% novel ingredients by volume by 2025; result 0.6% for Nutreco, 1.5% for Skretting, 0.3% for Trouw Nutrition; now judges novel ingredients on footprint, resilience, supplier readiness and customer value rather than volume. Target of 100% deforestation-free soy and palm by 2025; result 40% (Skretting 38%). Counts yeast and bacterial single-cell protein, mycoprotein and functional ingredients (prebiotics, probiotics, hydrolysates) as novel; screens them on food safety, nutrition, scalability, cost competitiveness and environmental and social impact',
  microbial_protein_trials_or_purchases='None found in Vietnam. Only novel ingredient in Vietnamese commercial feed is insect meal in shrimp feed from November 2025 (benchmark only)',
  standards_targets_and_timeline='RoadMap 2025 targets missed; no replacement volume target published in the 2025 impact report',
  relevance_to_t2='The one named buyer with a public novel-ingredient intake route (supplier form); its global share shows how slowly novel inputs enter feed even with a target',
  source_ids='FBA-07; FBA-08; FBA-04; VCO-28', evidence_label='VN-adjacent', confidence='High', demand_evidence_type='revealed; stated',
  notes='Group-wide figures, not Vietnam-specific; insect meal is cited as a benchmark, not a recommendation'),
 dict(actor_id='FBA-A02', actor='De Heus Vietnam', actor_type='livestock and aquafeed mill, multinational',
  vietnam_presence='21 plants; new shrimp feed mill (2024); marine R&D facility at Vinh Long (July 2024); 168,000 t a year marine and cold-water fish feed mill at Vinh Long (2026); bought CJ Feed and Care (closed 3 Mar 2026)',
  asc_status_sep_2026='Vinh Long 4 branch certified 23 Oct 2025 (v1.2, shrimp)',
  stated_ingredient_strategy='Aims for deforestation- and conversion-free soybean meal and palm on a mass-balance basis, with compensation credits where risk is high; names dependency on soy and feed additives from the United States, Brazil, Argentina and China as a strategic risk',
  microbial_protein_trials_or_purchases='None found; the 2025 sustainability report has no novel, single-cell, yeast, insect or algae ingredient target or trial',
  standards_targets_and_timeline='Global environmental and human rights due diligence process by end 2025',
  relevance_to_t2='Largest livestock buyer and a new premium shrimp and marine buyer; owns an in-country marine trial facility that could host a head-to-head trial',
  source_ids='FBA-12; FBA-04; VCO-08; VCO-09; VCO-10', evidence_label='VN-direct', confidence='Medium', demand_evidence_type='stated',
  notes='Clean negative on microbial ingredients in the 2025 report (text search)'),
 dict(actor_id='FBA-A03', actor='C.P. Vietnam (Charoen Pokphand Foods)', actor_type='integrated feed, farm and food group',
  vietnam_presence='Aquaculture business branch; new Ca Mau shrimp feed capacity of 124,800 t a year (2026)',
  asc_status_sep_2026='Aquaculture business branch certified 18 Jul 2025 (v1.2, shrimp)',
  stated_ingredient_strategy='Target of 100% of key raw materials (feed corn, soy, palm oil, cassava) from deforestation-free, traceable sources; 43% achieved in 2025; soy for poultry feed deforestation-free since January 2026; promotes probiotic-enriched feed',
  microbial_protein_trials_or_purchases='None found; the 2025 sustainability report does not mention single-cell or microbial protein',
  standards_targets_and_timeline='On-site ESG audits of critical and high-risk Tier 1 suppliers in Thailand and Vietnam by 2025',
  relevance_to_t2='Named first buyer; its stated feed innovation is probiotics, not protein',
  source_ids='FBA-11; FBA-04; IND-42', evidence_label='VN-adjacent', confidence='Medium', demand_evidence_type='stated',
  notes='Group figures mostly Thailand-based'),
 dict(actor_id='FBA-A04', actor='Grobest Vietnam', actor_type='shrimp feed mill, Taiwan-owned',
  vietnam_presence='Bien Hoa mill (Dong Nai); GROFARM model with 68 new farms in 2024; claims market leadership in Vietnam',
  asc_status_sep_2026='Certified 23 Jun 2025 (v1.2, shrimp)',
  stated_ingredient_strategy='Seeks alternative proteins that keep performance and cost-efficiency to ease reliance on fishmeal; 2024 certified sourcing: fishmeal 55%, soy 38%; sells functional feed lines (growth, immunity) and trialled immune functional feeds against EHP in Vietnam and Indonesia',
  microbial_protein_trials_or_purchases='Evaluated bacterial single-cell protein and fermented corn protein in recent years (results not published); in 2024 moved research to canola protein concentrate, which replaced up to 80% of fishmeal in a Taiwan trial',
  standards_targets_and_timeline='Six BAP-certified plants in 2024 (10 in 2022)',
  relevance_to_t2='The only named Vietnamese shrimp feed buyer with a disclosed microbial-protein evaluation; its move to a plant concentrate is a revealed preference on price and performance',
  source_ids='FBA-13; FBA-04', evidence_label='VN-direct', confidence='Medium', demand_evidence_type='revealed; stated',
  notes='Company report; market-leadership claim conflicts with the package view that Sheng Long is largest (see disagreements)'),
 dict(actor_id='FBA-A05', actor='Uni-President Vietnam', actor_type='feed, flour and food group, Taiwan-owned',
  vietnam_presence='Sites in Ho Chi Minh City (former Binh Duong), Dong Thap (former Tien Giang), Khanh Hoa (former Ninh Thuan) and Da Nang (former Quang Nam)',
  asc_status_sep_2026='Quang Nam branch certified 13 Nov 2025 (v1.01, shrimp)',
  stated_ingredient_strategy='Named ASC certification as a 2026 priority; quoted fishmeal at USD 1,600 per t (November 2025); website gives no ingredient strategy',
  microbial_protein_trials_or_purchases='None found',
  standards_targets_and_timeline='None published',
  relevance_to_t2='Named first buyer; no public signal beyond ASC',
  source_ids='FM-04; VCO-29; FBA-04', evidence_label='VN-direct', confidence='Low', demand_evidence_type='stated',
  notes=''),
 dict(actor_id='FBA-A06', actor='Sheng Long Bio-Tech (Haid Group)', actor_type='shrimp and fish feed mill, China-owned',
  vietnam_presence='Haid and Thang Long (Sheng Long) Vinh Long complex, 650,000 t a year; Haid plant in Hai Phong (former Hai Duong), 700,000 t a year claimed',
  asc_status_sep_2026='Certified 11 Mar 2026 (v1.01, shrimp and marine finfish)',
  stated_ingredient_strategy='Named ASC certification as a 2026 priority; expected shrimp feed sales to grow about 15% in 2026',
  microbial_protein_trials_or_purchases='Not found; Haid website could not be fetched (robots or server error), so the parent strategy was not read',
  standards_targets_and_timeline='None read',
  relevance_to_t2='Largest shrimp feed maker by capacity in the package; parent is a Chinese group with direct access to Chinese microbial proteins',
  source_ids='FM-04; IND-46; IND-43; FBA-04', evidence_label='VN-direct', confidence='Low', demand_evidence_type='stated',
  notes='Gap: Haid annual report not read'),
 dict(actor_id='FBA-A07', actor='Tongwei Vietnam', actor_type='aquafeed mill, China-owned',
  vietnam_presence='Top-six shrimp feed maker; raised shrimp feed prices by VND 1,200 to 1,500 per kg in June 2026',
  asc_status_sep_2026='Initial audit (shrimp)',
  stated_ingredient_strategy='Group feed capacity about 13 Mt a year; 2025 ESG report describes precision aquatic nutrition and microalgae R&D on protein substitution and phycocyanin',
  microbial_protein_trials_or_purchases='None found; the 2025 ESG report has no single-cell, microbial or yeast protein and no fishmeal or soybean-meal reduction target (Chinese-language text search)',
  standards_targets_and_timeline='None found for Vietnam',
  relevance_to_t2='Named first buyer entering ASC; its group R&D points to algae, not yeast or bacteria',
  source_ids='FBA-14; FM-10; FBA-04', evidence_label='VN-adjacent', confidence='Medium', demand_evidence_type='stated',
  notes='Clean negative for microbial protein in the group ESG report'),
 dict(actor_id='FBA-A08', actor='BioMar Viet Uc (Viet Uc Aqua Feed)', actor_type='shrimp feed joint venture of BioMar (Denmark) and Viet-Uc',
  vietnam_presence='Factory run with Viet-Uc, one of the largest shrimp farmers in Vietnam; ramp-up volumes cited in BioMar H1 2026 results',
  asc_status_sep_2026='Certified 11 Jul 2026 (v1.2, shrimp); first ASC-certified BioMar plant in Asia',
  stated_ingredient_strategy='BioMar target of 50% circular and restorative ingredients by 2030; 27.4% in 2024; lists commercialisation of novel raw materials as a strategic aim',
  microbial_protein_trials_or_purchases='None found for Vietnam',
  standards_targets_and_timeline='50% circular and restorative by 2030',
  relevance_to_t2='New premium shrimp buyer tied to an integrated shrimp farmer; a plausible trial partner',
  source_ids='FBA-09; FBA-10; FBA-24; FBA-04', evidence_label='VN-direct', confidence='Medium', demand_evidence_type='stated',
  notes='BioMar took a DKK 36 million goodwill write-down in Vietnam in 2023'),
 dict(actor_id='FBA-A09', actor='Cargill Vietnam', actor_type='livestock feed and premix, multinational',
  vietnam_presence='About 1,100 staff; 11 plants (2023); Provimi premix plant of 40,000 t a year in Dong Nai',
  asc_status_sep_2026='Not in the ASC register',
  stated_ingredient_strategy='Website lists livestock, poultry and aquatic feed, supplements and additives; no ingredient strategy found',
  microbial_protein_trials_or_purchases='None found',
  standards_targets_and_timeline='None found; global aqua sustainability page returned 404',
  relevance_to_t2='Premix plant is a route for micro-inclusion functional ingredients; package reports an exit from aquafeed in May 2025',
  source_ids='FBA-16; IND-47; IND-43', evidence_label='VN-direct', confidence='Low', demand_evidence_type='stated',
  notes='Disagreement on whether Cargill still makes aquafeed in Vietnam'),
 dict(actor_id='FBA-A10', actor='GreenFeed Vietnam', actor_type='livestock and aquafeed mill, Vietnamese',
  vietnam_presence='Among the livestock feed leaders',
  asc_status_sep_2026='Certified 1 Aug 2025 (v1.2, pangasius, tilapia, seabass and seabream)',
  stated_ingredient_strategy='Not read',
  microbial_protein_trials_or_purchases='None found',
  standards_targets_and_timeline='None read',
  relevance_to_t2='Pangasius and marine fish buyer with ASC scope',
  source_ids='FBA-04; MAC-25', evidence_label='VN-direct', confidence='Low', demand_evidence_type='revealed',
  notes='Register entry only'),
 dict(actor_id='FBA-A11', actor='Feed One JSC (Vinh Hoan, 75%)', actor_type='feed arm of the largest pangasius exporter',
  vietnam_presence='My Hiep industrial cluster, Dong Thap; makes livestock and aquatic feeds; became a joint stock company on 26 Jun 2026',
  asc_status_sep_2026='Certified 16 Jul 2024 (v1.2, pangasius and tilapia)',
  stated_ingredient_strategy='Parent Vinh Hoan contracted at least 15,000 t of insect meal over 2025 to 2027 for pangasius feed (benchmark only)',
  microbial_protein_trials_or_purchases='None found',
  standards_targets_and_timeline='None published for feed',
  relevance_to_t2='Integrated buyer that has already signed a multi-year novel-ingredient offtake; the template an anchor buyer for T2 would follow',
  source_ids='FBA-15; FBA-04; EXP-50; ECO-05', evidence_label='VN-direct', confidence='High', demand_evidence_type='revealed',
  notes='Insect meal is a benchmark, never a recommendation'),
 dict(actor_id='FBA-A12', actor='Pangasius exporters with their own feed mills (Nam Viet, Sao Mai, Godaco)', actor_type='integrated pangasius exporters',
  vietnam_presence='Mekong Delta',
  asc_status_sep_2026='Nam Viet Aquaculture Feed certified 5 Aug 2026 (v1.2); Sao Mai Super Feed certified 7 May 2026 (v1.01); Godaco Vinh Long branch in initial audit',
  stated_ingredient_strategy='Not read',
  microbial_protein_trials_or_purchases='None found',
  standards_targets_and_timeline='ASC certification of own feed in 2026',
  relevance_to_t2='Integrated groups are feed buyers and feed makers at once; five of the nine ASC pangasius mills belong to exporters or their feed arms (our reading of names)',
  source_ids='FBA-04', evidence_label='VN-direct', confidence='Low', demand_evidence_type='revealed',
  notes='Ownership inferred from company names; verify'),
 dict(actor_id='FBA-A13', actor='Minh Phu Seafood', actor_type='integrated shrimp exporter',
  vietnam_presence='Ca Mau; supplies more than 70 countries',
  asc_status_sep_2026='No feed mill in the ASC register',
  stated_ingredient_strategy='No feed, certification or ingredient information on the company website',
  microbial_protein_trials_or_purchases='None found',
  standards_targets_and_timeline='None found',
  relevance_to_t2='Clean negative: the largest shrimp exporter shows no public feed-ingredient pull',
  source_ids='FBA-23', evidence_label='VN-direct', confidence='Low', demand_evidence_type='stated',
  notes=''),
 dict(actor_id='FBA-S01', actor='Aquaculture Stewardship Council (ASC), Feed Standard v1.2', actor_type='standard setter',
  vietnam_presence='15 certified Vietnamese mills and 6 in initial audit (register, 25 Sep 2026); Vietnam has the most certified mills of any country (15 of 114)',
  asc_status_sep_2026='n/a',
  stated_ingredient_strategy='Soy and palm: public deforestation- and conversion-free commitment with a cut-off no later than 31 Dec 2020; eligible soy and palm volume must at least equal the volume in ASC feed sold. Marine: majority sustainability level must rise one level every three years. GHG: kg CO2e per tonne of feed calculated and reported annually, no reduction target',
  microbial_protein_trials_or_purchases='Feed stuffs (for example land animal, algae or insect-based) need due diligence on the ingredient maker only and count as eligible; any unique ingredient under 1% of a mill\'s annual aquafeed ingredient intake counts as eligible. No requirement or credit for microbial protein',
  standards_targets_and_timeline='v1.2 released 19 Dec 2025; effective and mandatory 2 Feb 2026; medium-risk ingredients may be used as non-eligible until 2 Feb 2029',
  relevance_to_t2='Neutral: a microbial ingredient at 1 to 5% inclusion carries little compliance cost and earns no premium',
  source_ids='FBA-01; EXP-30; FBA-04', evidence_label='general', confidence='High', demand_evidence_type='revealed',
  notes='Rules are revealed evidence of what certified buyers require'),
 dict(actor_id='FBA-S02', actor='ASC Farm Standard v1.0.1A2', actor_type='standard setter (farm level)',
  vietnam_presence='Applies to ASC shrimp and pangasius farms',
  asc_status_sep_2026='n/a',
  stated_ingredient_strategy='Indicator 1.4.3: compound feed must come from a mill certified to the ASC Feed Standard and be traceable as ASC-conforming; 1.4.4: disclose to buyers when feed contains more than 0.9% GMO',
  microbial_protein_trials_or_purchases='No ingredient-specific rule',
  standards_targets_and_timeline='Issued and effective 5 Aug 2026; all audits from 1 May 2028 against this standard, when species standards become inactive',
  relevance_to_t2='From May 2028 ASC farms buy from ASC mills, so mills will ask ingredient makers for due-diligence data; a genetically modified production strain would add to GMO disclosure, which soybean meal already triggers',
  source_ids='FBA-02; FBA-03', evidence_label='general', confidence='Medium', demand_evidence_type='revealed',
  notes='Indicator text read through a page summary, not the PDF'),
 dict(actor_id='FBA-S03', actor='Best Aquaculture Practices (BAP), Feed Mill Standard Issue 3.3 and Amendment 1', actor_type='standard setter',
  vietnam_presence='Grobest runs BAP-certified plants; BAP is the main scheme for US buyers',
  asc_status_sep_2026='n/a',
  stated_ingredient_strategy='At least 75% of fishmeal and fish oil from certified sources or approved fishery improvement projects (suspended to 1 Jul 2027 where neither is produced nationally); at least 50% certified soy; 100% RSPO palm; a published, time-bound plan to 100% deforestation- and conversion-free soy by 1 Jan 2026; fishmeal and oil inclusion shown on feed documents',
  microbial_protein_trials_or_purchases='Amendment 1 (5 Aug 2026): ingredients from algae and other aquatic microorganisms count towards the 75% by mass balance, with new data points on their share',
  standards_targets_and_timeline='Issue 3.3 published 8 Sep 2025, effective 22 Dec 2025; Amendment 1 effective 5 Aug 2026',
  relevance_to_t2='Small, unclear credit: whether yeast or bacterial biomass grown on cassava sugar counts as an aquatic microorganism is not stated; clearer for microalgae',
  source_ids='FBA-05; FBA-13', evidence_label='general', confidence='High', demand_evidence_type='revealed',
  notes=''),
 dict(actor_id='FBA-S04', actor='GLOBALG.A.P. Compound Feed Manufacturing (CFM) v3.1', actor_type='standard setter',
  vietnam_presence='Grobest Vietnam holds GLOBALG.A.P. certification',
  asc_status_sep_2026='n/a',
  stated_ingredient_strategy='Mandatory for feed supplied to GLOBALG.A.P.-certified aquaculture farms; excludes IUU and endangered marine ingredients; plant ingredients sourced in line with FEFAC soy guidelines',
  microbial_protein_trials_or_purchases='No novel-ingredient or GHG requirement found',
  standards_targets_and_timeline='Published 20 Dec 2022; replaced v2.2 and v3 on 1 Jan 2024',
  relevance_to_t2='Neutral',
  source_ids='FBA-06; FBA-13', evidence_label='general', confidence='Medium', demand_evidence_type='revealed',
  notes=''),
 dict(actor_id='FBA-S05', actor='UK retailers (UK Soy Manifesto signatories)', actor_type='buyer group',
  vietnam_presence='Buyers of Vietnamese shrimp through importers',
  asc_status_sep_2026='n/a',
  stated_ingredient_strategy='All soy shipped to the UK or embedded in products, including aquaculture feed, deforestation- and conversion-free (cut-off 2020 at the latest) by the end of 2025; 51 signatories including Tesco, Sainsbury\'s, Aldi, Lidl, M&S, Morrisons, Co-op, Waitrose; 49 have policies, 43 report publicly, 42 have action plans',
  microbial_protein_trials_or_purchases='No novel-feed requirement found',
  standards_targets_and_timeline='Deadline end 2025 passed; no aggregate share achieved published on the site',
  relevance_to_t2='Pull is for traceable soy; a 1 to 5% microbial ingredient displaces little soy',
  source_ids='EXP-33', evidence_label='general', confidence='Medium', demand_evidence_type='stated',
  notes='Progress counts read 25 Sep 2026'),
 dict(actor_id='FBA-S06', actor='European Union Deforestation Regulation (EUDR)', actor_type='regulator',
  vietnam_presence='Applies to soy products placed on the EU market',
  asc_status_sep_2026='n/a',
  stated_ingredient_strategy='Covers cattle, wood, cocoa, soy, palm oil, coffee, rubber and listed derived products; fish and crustaceans are not covered commodities',
  microbial_protein_trials_or_purchases='Not applicable',
  standards_targets_and_timeline='Applies from 30 Dec 2026 (large and medium operators) and 30 Jun 2027 (micro and small)',
  relevance_to_t2='None directly: Vietnamese shrimp and pangasius exports fall outside it (our reading); the soy pull on Vietnamese feed runs through retailer and certification rules, not EUDR',
  source_ids='EXP-27; EXP-28', evidence_label='general', confidence='Medium', demand_evidence_type='revealed',
  notes='Our reading of scope; confirm with the Commission scope guidance'),
]
write('data_feed_buyer_register.csv', reg)

std = [
 dict(standard_id='FBA-ST-01', standard_or_rule='ASC Feed Standard', owner='Aquaculture Stewardship Council', version='1.2',
  published='19 Dec 2025', effective='2 Feb 2026 (mandatory)', key_dates='Medium-risk ingredients may be sourced as non-eligible until 2 Feb 2029',
  marine_ingredients='Whole-fish marine ingredients scored on four sustainability levels; majority level rises one level every three years; by-products eligible if low risk',
  soy_and_plant_ingredients='Public deforestation- and conversion-free commitment; soy and palm cut-off no later than 31 Dec 2020; eligible soy and palm volume at least equal to that in ASC feed sold (new in v1.2)',
  novel_or_microbial_ingredients='Feed stuffs (algae, insect, land animal) need due diligence on the ingredient maker only; any unique ingredient under 1% of annual aquafeed ingredient intake is eligible; no requirement or credit for microbial protein',
  ghg='kg CO2e per tonne of feed calculated and reported publicly each year; species-specific data to farms on request; no reduction target',
  what_it_means_for_t2='Neutral: low compliance cost, no premium',
  source_ids='FBA-01; EXP-30', evidence_label='general', confidence='High', demand_evidence_type='revealed', notes='v1.1 (May 2025) never took effect'),
 dict(standard_id='FBA-ST-02', standard_or_rule='ASC Farm Standard', owner='Aquaculture Stewardship Council', version='1.0.1A2',
  published='5 Aug 2026', effective='5 Aug 2026; mandatory for all audits from 1 May 2028',
  key_dates='Species standards become inactive on 1 May 2028',
  marine_ingredients='Through the feed mill', soy_and_plant_ingredients='Through the feed mill',
  novel_or_microbial_ingredients='None; GMO disclosure to buyers when feed contains more than 0.9% GMO (indicator 1.4.4)',
  ghg='Energy and GHG criterion at farm level (2.10)',
  what_it_means_for_t2='From May 2028 certified farms need feed from ASC-certified mills (indicator 1.4.3), so mills will need ingredient due-diligence data',
  source_ids='FBA-02; FBA-03', evidence_label='general', confidence='Medium', demand_evidence_type='revealed', notes='Indicator wording from a page summary'),
 dict(standard_id='FBA-ST-03', standard_or_rule='BAP Feed Mill Standard', owner='Global Seafood Alliance', version='Issue 3.3, Amendment 1',
  published='8 Sep 2025 (Issue 3.3)', effective='22 Dec 2025 (Issue 3.3); 5 Aug 2026 (Amendment 1)',
  key_dates='Deforestation- and conversion-free soy plan due 1 Jan 2026; marine minimum suspended to 1 Jul 2027 where no certified or FIP material is produced nationally',
  marine_ingredients='At least 75% of fishmeal and fish oil from certified sources or approved fishery improvement projects (mass balance); inclusion rates declared on feed documents',
  soy_and_plant_ingredients='At least 50% certified soy (ProTerra, RTRS, SSAP or FEFAC-compliant); 100% RSPO palm; time-bound plan to 100% deforestation- and conversion-free soy',
  novel_or_microbial_ingredients='Ingredients from algae and other aquatic microorganisms count towards the 75% marine target; new data points on their share of meal and oil',
  ghg='Not found in the sustainability clauses read',
  what_it_means_for_t2='Possible small credit, only if a terrestrial fermentation biomass is accepted as an aquatic microorganism (not stated)',
  source_ids='FBA-05', evidence_label='general', confidence='High', demand_evidence_type='revealed', notes=''),
 dict(standard_id='FBA-ST-04', standard_or_rule='GLOBALG.A.P. Compound Feed Manufacturing', owner='GLOBALG.A.P.', version='3.1',
  published='20 Dec 2022', effective='1 Jan 2024', key_dates='Mandatory for feed supplied to certified aquaculture producers',
  marine_ingredients='No IUU or IUCN Red List and CITES-listed species', soy_and_plant_ingredients='Sourcing in line with FEFAC soy guidelines; no illegal deforestation or high conservation value areas',
  novel_or_microbial_ingredients='None found', ghg='None found',
  what_it_means_for_t2='Neutral', source_ids='FBA-06', evidence_label='general', confidence='Medium', demand_evidence_type='revealed', notes='Page summary; checklists not read'),
 dict(standard_id='FBA-ST-05', standard_or_rule='UK Soy Manifesto', owner='UK retailers and food businesses (51 signatories)', version='n/a',
  published='n/a', effective='Deadline end 2025', key_dates='Progress: 49 of 51 with policies, 43 reporting, 42 with action plans (read 25 Sep 2026)',
  marine_ingredients='Not covered', soy_and_plant_ingredients='All soy, including soy embedded in animal and aquaculture feed, deforestation- and conversion-free with a cut-off of 2020 at the latest',
  novel_or_microbial_ingredients='None', ghg='None', what_it_means_for_t2='Weak: pull is on soy traceability',
  source_ids='EXP-33', evidence_label='general', confidence='Medium', demand_evidence_type='stated', notes=''),
 dict(standard_id='FBA-ST-06', standard_or_rule='EU Deforestation Regulation', owner='European Union', version='Regulation (EU) 2023/1115 as revised',
  published='2023; revised December 2025', effective='30 Dec 2026 (large and medium); 30 Jun 2027 (micro and small)',
  key_dates='New derived products from 30 Dec 2027', marine_ingredients='Not covered',
  soy_and_plant_ingredients='Soy and derived products placed on the EU market', novel_or_microbial_ingredients='Not applicable', ghg='Not applicable',
  what_it_means_for_t2='None directly; seafood is not a covered commodity (our reading)',
  source_ids='EXP-27; EXP-28; GEO-07', evidence_label='general', confidence='Medium', demand_evidence_type='revealed', notes=''),
 dict(standard_id='FBA-ST-07', standard_or_rule='Vietnam feed permitted lists', owner='MAE (DLPAH for livestock; DFFI for aquafeed)', version='Circular 21/2019 Appendix VI as amended by Circular 31/2022; Circular 16/2026 Appendix II',
  published='2019 to 2026', effective='Inactive yeasts listed for livestock since 20 Feb 2023; aquafeed list from 9 Mar 2026; fines for unlisted livestock raw materials from 5 Aug 2026',
  key_dates='No 2024 to 2026 entry for single-cell protein or microbial biomass found',
  marine_ingredients='n/a', soy_and_plant_ingredients='n/a',
  novel_or_microbial_ingredients='Livestock: Torula or Candida yeast, molasses yeast, dried yeast and amino-acid fermentation by-products listed. Aquafeed: Candida utilis, Pichia farinosa and Saccharomyces listed only as microorganisms; beta-glucan as a bioactive; no raw-material section',
  ghg='n/a', what_it_means_for_t2='A yeast product has a route; a bacterial or new fungal biomass needs a trial; aquafeed status needs a written DFFI opinion',
  source_ids='REG-32; REG-33; REG-40; REG2-01; REG2-10', evidence_label='VN-direct', confidence='High', demand_evidence_type='revealed', notes='From the package; product registers could not be reached this wave'),
]
write('data_feed_standards_timeline.csv', std)

yeast_bulk, yeast_spec = 1100, 8550
feeds = {'shrimp': (1270, 1920), 'pangasius': (385, 770)}
costs = {'low end of the indicative cost stack': 2227, 'high end of the indicative cost stack': 6612}
pp = []
i = 1
for sp, (fl, fh) in feeds.items():
    for cn, c in costs.items():
        for inc in (1, 2, 5):
            gap = (c - yeast_bulk) * inc / 100
            pp.append(dict(scenario_id=f'FBA-PP-{i:02d}', species=sp, t2_cost_case=cn, t2_cost_usd_per_t=c,
                comparator='imported bulk inactive yeast, 2025 (FOB)', comparator_price_usd_per_t=yeast_bulk, inclusion_pct=inc,
                extra_cost_usd_per_t_feed=round(gap, 1), feed_price_usd_per_t=f'{fl} to {fh}',
                gain_needed_pct_of_feed_cost=f'{gap/fh*100:.1f} to {gap/fl*100:.1f}',
                source_ids='FBA-17; FM-04; COST-43; COST-44', evidence_label='VN-direct', confidence='Low', demand_evidence_type='inferred',
                notes='Our calculation: (T2 cost minus bulk yeast price) x inclusion / feed price; the gain is the extra feed-cost saving (for example feed conversion or survival) a head-to-head trial must show over commodity yeast'))
            i += 1
for cn, c in costs.items():
    pp.append(dict(scenario_id=f'FBA-PP-{i:02d}', species='any', t2_cost_case=cn, t2_cost_usd_per_t=c,
        comparator='imported specialty yeast products, 2025 (FOB, unit value USD 2 per kg or more)', comparator_price_usd_per_t=yeast_spec, inclusion_pct='',
        extra_cost_usd_per_t_feed='', feed_price_usd_per_t='', gain_needed_pct_of_feed_cost=f'none: T2 cost is USD {yeast_spec - c:,} per t below the specialty unit value',
        source_ids='FBA-17; COST-43; COST-44', evidence_label='VN-direct', confidence='Low', demand_evidence_type='inferred',
        notes='Specialty tier was only 464 t (USD 3.97 million) in 2025, half of it from Japan, probably not all feed; to compete here T2 must match branded yeast fractions on documented function'))
    i += 1
pp.append(dict(scenario_id=f'FBA-PP-{i:02d}', species='any', t2_cost_case='variable cost only (tolled; no capital, labour or land)', t2_cost_usd_per_t='883 to 1,905',
    comparator='imported bulk inactive yeast, 2025 (FOB)', comparator_price_usd_per_t=yeast_bulk, inclusion_pct='', extra_cost_usd_per_t_feed='', feed_price_usd_per_t='',
    gain_needed_pct_of_feed_cost='Variable cost alone spans the bulk yeast price',
    source_ids='COST-01; COST-06; COST-16; COST-32; COST-33; FM-01; FBA-17', evidence_label='VN-direct', confidence='Low', demand_evidence_type='inferred',
    notes='Our calculation from the app-i cost lines: carbon 600 to 1,100, nitrogen 72 to 145, minerals 50 to 150, electricity 58 to 117, cooling 7 to 117, steam 78 to 218, water 18 to 58 USD per t of product'))
write('data_t2_price_per_performance.csv', pp)
print(len(reg), len(std), len(pp))
