import csv
def w(name, header, rows):
    with open(name,'w',newline='',encoding='utf-8') as f:
        x=csv.writer(f); x.writerow(header); x.writerows(rows)
    s=open(name,encoding='utf-8').read(); assert chr(0x2013) not in s and chr(0x2014) not in s, name

w('key_numbers.csv',['label','value','unit','as_of','context','source_ids','evidence','confidence','demand_evidence_type'],[
 ['Inactive yeast and dead single-cell organisms imported by Vietnam (HS 2102.20)','9,193 (USD 13.5 million)','t','2025','Partner-reported FOB; lower bound because Cambodia had not reported; 3,828 t in 2019, so 2.4 times; 9,336 t in 2024; food and feed not separable at HS6','FBA-17','VN-direct','Medium','revealed'],
 ['Price of the bulk tier of imported inactive yeast','1.10','USD per kg (FOB)','2025','8,729 t, 95% of tonnage, unit value below USD 2 per kg (China USD 1.27, Brazil 1.10, Serbia 0.87); specialty tier 464 t at USD 8.55 per kg; the price a Vietnamese T2 product must meet or beat on performance','FBA-17','VN-direct','Medium','revealed'],
 ['ASC Feed Standard certified feed mills in Vietnam','15 of 114 worldwide (plus 6 in initial audit)','certified mills','2026-09-25','Most of any country; Ecuador and Turkey 8 each; ASC farm audits require ASC-certified feed from 1 May 2028','FBA-04; FBA-02','VN-direct','High','revealed'],
 ['Novel-ingredient share of feed, Nutreco group (Skretting)','0.6 (1.5)','% of ingredient volume','2025','Against a RoadMap 2025 target of 5 to 10%; Skretting counts yeast and bacterial single-cell protein, mycoprotein and functional ingredients as novel; group-wide, not Vietnam','FBA-07; FBA-08','VN-adjacent','High','revealed'],
 ['Average fishmeal import price paid by Vietnam','1,622 (India 1,728)','USD per t (FOB, all grades)','2026-01 to 2026-07','Partner-reported, partial; up about 39% on 2025 (USD 1,163); World Bank Peru 65% CIF benchmark USD 1,832 (Q1) to 2,145 (June) and 2,500 in August 2026','FBA-20; FM-01','VN-direct','Low','revealed'],
 ['Head-to-head gain a T2 product must show over commodity yeast (2% inclusion, low end of cost stack)','1.2 to 1.8 (shrimp); 2.9 to 5.9 (pangasius)','% of feed cost','2026','Our calculation: (USD 2,227 minus 1,100 per t) x 2% / feed price (shrimp USD 1,270 to 1,920 per t; pangasius USD 385 to 770 per t); 5.7 to 8.7 and 14.3 to 28.6 at the high end of the stack (USD 6,612)','FBA-17; FM-04; COST-43; COST-44','VN-direct','Low','inferred'],
])

w('open_questions.csv',['question','why_it_matters','cheapest_way_to_close','owner_org_to_ask','priority'],[
 ['Who imports HS 2102.20.10 (yeast of a kind used in animal feeding) and 2102.20.90, in what tonnage, 2024 to 2026?','Names T2 buyers and splits feed from food in the 9,200 t pool; three or more ASC mills each importing 500 t or more would meet the market-pull rubric of 5; mostly food or pet food would cut it to 3','Declaration-level customs extract for 2102.20 by importer and description (extend DMV-02)','General Department of Customs; a trade-data vendor; Vietnam Animal Feed Association','High'],
 ['Which yeast products do Vietnamese shrimp and pangasius mills use, at what dose and price, and what gain do they measure?','Turns the inferred price-per-performance hurdle (1.2 to 1.8% of shrimp-feed cost) into a stated or tested one; sets the head-to-head trial design','Three structured calls with nutritionists at Grobest, Skretting Vietnam, De Heus (Vinh Long marine R&D centre) and Sheng Long','Grobest; Skretting Vietnam; De Heus Vietnam; Sheng Long','High'],
 ['What happened in Grobest\'s evaluation of bacterial single-cell protein (species, product, inclusion, result, price)?','The only disclosed microbial-protein test by a leading Vietnamese shrimp-feed maker; a negative on price or performance is the closest thing to a T2 kill-test result','Written question to Grobest\'s sustainability or R&D team','Grobest Group','Medium'],
 ['Would BAP count yeast or bacterial biomass grown on sugar as an ingredient from "other aquatic microorganisms" under Feed Mill Standard clause 4.6 (Amendment 1)?','Decides whether T2 or T3 products earn credit towards BAP\'s 75% marine-ingredient target, or only microalgae do','One email to the Global Seafood Alliance standards team','Global Seafood Alliance','Medium'],
 ['How much spent brewer\'s yeast and amino-acid fermentation biomass is produced in Vietnam, and where does it go now?','The revealed price (about USD 1.1 per kg) is set by by-product yeasts; a domestic by-product stream is the only T2 route that can meet it','Company sustainability reports and direct questions (links to OQ-017 and OQ-018)','Heineken Vietnam; Sabeco; Vedan; Ajinomoto Vietnam','Medium'],
 ['Who exports the 8,166 t of HS 2102.20 that left Vietnam in 2025, and is any of it feed grade?','Domestic yeast plants are T2\'s nearest competitors and possible tolling partners','Ask AB Mauri Vietnam and Lesaffre (Saf-Viet); exporter-level customs data','AB Mauri Vietnam; Saf-Viet (Lesaffre); General Department of Customs','Low'],
 ['Will Vinh Hoan\'s Feed One or another integrated pangasius group sign a trial or offtake for a non-insect microbial ingredient?','An anchor buyer is what investors and DFIs ask for (wave 7 AIS-Q14); none found','Direct approach to Vinh Hoan investor relations and Feed One management','Vinh Hoan Corporation; Nam Viet; Sao Mai Group','Medium'],
])

w('disagreements.csv',['topic','claim_a','claim_b','position_taken','notes'],[
 ['Number of Vietnamese feed mills in the ASC programme','VASEP report of 22 Sep 2026: 20 mills in the programme, 13 certified (EXP-32)','ASC Find a Feed Mill register queried 25 Sep 2026: 23 records, 15 certified, 6 in initial audit, 1 not awarded, 1 incomplete (FBA-04)','Use the register, with its date; the difference is probably timing (Viet Uc and Proconco certified in July and August 2026, Nam Viet in August) or counting method','Both revealed; register is primary'],
 ['Tonnage of Vietnam\'s HS 2102.20 imports','Vietnam-reported 2023: USD 9.65 million, 1,934 t (net weight flagged as estimated by Comtrade) (FBA-18)','Partner-reported 2023: USD 10.44 million, 9,605 t (FBA-17)','Use partner-reported tonnage; Vietnam-reported weights are imputed with one unit value for all partners; report both values','Values also differ in 2019 and 2020 (USD 5.98 and 5.91 million against 8.28 and 10.43 million); do not average'],
 ['Price of fishmeal to Vietnamese mills','World Bank Peru 65% protein, CIF: USD 1,706 per t (2025), 2,500 per t (August 2026) (FM-01)','Partner-reported FOB exports to Vietnam, all grades: USD 1,163 per t (2025), 1,622 per t (January to July 2026, partial) (FBA-20)','Keep the World Bank series as the international benchmark and add the mirror series as what Vietnam pays; do not average','Different grade, basis (CIF against FOB) and coverage'],
 ['Largest shrimp-feed maker in Vietnam','Package: Sheng Long (Haid) is the largest shrimp feed maker (650,000 t a year complex) (FAC-054; IND-46)','Grobest 2024 report: "retained market leadership in Vietnam" (FBA-13)','Neither verified; keep the package view on capacity and record Grobest\'s claim as a company statement','The segment behind Grobest\'s claim is not stated'],
 ['Whether Cargill still makes aquafeed in Vietnam','Package: Cargill exited aquafeed in May 2025, closing its Dong Thap and Long An aquafeed plants (FAC-058; IND-47, Low)','Cargill Vietnam website (25 Sep 2026) lists aquatic feed among its solutions (FBA-16)','Keep the exit as Low confidence; the website may be generic; ask Cargill','Cargill is not in the ASC feed register'],
 ['Which ASC Feed Standard text ch27 relies on','ch27.5 cites the v1.1 text (EXP-29, May 2025)','ASC states v1.1 never took effect and v1.2 (19 Dec 2025) has been mandatory since 2 Feb 2026 (EXP-30; FBA-01)','Cite v1.2; the cut-off date and GHG rules are unchanged, and v1.2 adds the eligible-volume rule for soy and palm and a medium-risk exception to 2 Feb 2029','Correction of citation, not of substance'],
])
print('ok')
