import csv
A = '2026-09-25'
CT = 'https://comtradeapi.un.org/public/v1/preview/C/'
S = [
('FBA-01','Aquaculture Stewardship Council. ASC Feed Standard, version 1.2 (ASC-STD-002). Released 19 December 2025, effective 2 February 2026.','ASC Feed Standard v1.2','Aquaculture Stewardship Council','2025-12-19','https://programme-centre.asc-aqua.org/app/uploads/2025/12/ASC-STD-002-ASC-Feed-Standard-V1.2-December-2025.pdf','','other','Full text read (143 pages, text extraction): version table; 2.2.9 medium-risk exception to 2 Feb 2029; 3.2.2 and 5.1.10 eligible soy and palm volume; 4.1.1 majority sustainability level; 5.1.2 cut-off 31 Dec 2020; 1.21.4 and 1.21.5 GHG reporting; Appendix 3 due diligence levels; eligible and non-eligible ingredient lists incl. feed stuffs and the under-1% rule. Standard setter (source_type other).'),
('FBA-02','Aquaculture Stewardship Council. ASC Farm Standard programme page (v1.0.1A2). Accessed 25 September 2026.','ASC Farm Standard v1','Aquaculture Stewardship Council','2026-08-05','https://programme-centre.asc-aqua.org/farm-v1/','','other','States v1.0.1A2 issued and effective 5 Aug 2026; mandatory transition date extended to 1 May 2028, after which audits use this standard and species standards become inactive. Read through a page summary.'),
('FBA-03','Aquaculture Stewardship Council. ASC Farm Standard v1.0.1A2, standard text web page, criterion 1.4. Accessed 25 September 2026.','ASC Farm Standard: criterion 1.4 traceability and disclosure','Aquaculture Stewardship Council','2026-08-05','https://programme-centre.asc-aqua.org/farm-v1/farm-standard/','','other','Indicator 1.4.3 (compound feed from ASC Feed Standard certified mills, traceable as ASC-conforming); 1.4.4 (disclose feed with more than 0.9% GMO). Read through a page summary, not the PDF: Medium.'),
('FBA-04','Aquaculture Stewardship Council. Find a Feed Mill register, all records, queried through the site search (collection v_Find_FeedMill) on 25 September 2026.','ASC Find a Feed Mill','Aquaculture Stewardship Council','2026-09-25','https://asc-aqua.org/find-feed-mill/','','database','140 records worldwide, 114 certified; Viet Nam 23 records: 15 certified, 6 in initial audit, 1 not awarded, 1 incomplete (cancelled). Saved as raw/asc_mills.json.'),
('FBA-05','Global Seafood Alliance. BAP Feed Mill Standard, Issue 3.3, with Amendment 1 effective 5 August 2026.','BAP Feed Mill Standard Issue 3.3, Amendment 1','Global Seafood Alliance (Best Aquaculture Practices)','2026-08-05','https://www.bapcertification.org/Downloadables/pdf/standards/BAP%20-%20Feed%20Mill%20Standard%20-%20Issue%203.3%20-%20Amendment%201%20-%2005-August-2026.pdf','','other','Read in text: Issue 3.3 published 8 Sep 2025, effective 22 Dec 2025; Amendment 1 clauses 4.6 and 4.7 (algae and other aquatic microorganism ingredients count towards 75%; suspension to 1 Jul 2027); section 4 sustainability of fishmeal, fish oil, soy and palm (50% certified soy; 100% DCF soy plan by 1 Jan 2026; RSPO palm).'),
('FBA-06','GLOBALG.A.P. Compound Feed Manufacturing (CFM) solution page. Accessed 25 September 2026.','Compound Feed Manufacturing','GLOBALG.A.P.','2026','https://www.globalgap.org/what-we-offer/solutions/compound-feed-manufacturing/','','other','CFM v3.1 published 20 Dec 2022, replaced v2.2 and v3 on 1 Jan 2024; mandatory for feed supplied to IFA-certified aquaculture; IUU exclusion; FEFAC soy guidelines. Page summary; checklists not read.'),
('FBA-07','Nutreco. Impact Report 2025.','Nutreco Impact Report 2025','Nutreco','2026','https://www.nutreco.com/siteassets/nutrecocorp-documents/sustainability-reports/nutreco-impact-report-2025.pdf','','company','Read in text: RoadMap 2025 target 5 to 10% novel ingredients by volume; 2025 result Nutreco 0.6%, Skretting 1.5%, Trouw 0.3% (pp. 63 to 64); Skretting Vietnam insect meal in shrimp feed (p. 65); 100% deforestation-free soy and palm target, 40% achieved (Skretting 38%) (pp. 66, 72).'),
('FBA-08','Skretting. How does Skretting define novel ingredients? Web page. Accessed 25 September 2026.','How does Skretting define novel ingredients','Skretting (Nutreco)','2026','https://www.skretting.com/en/sustainability/novel-ingredients/how-does-skretting-define-novel-ingredients/','','company','Definition and 12 categories incl. yeast SCP, bacterial SCP, mycoprotein and functional ingredients; assessment on food safety, nutritional value, scalability, cost competitiveness, environmental and social impact.'),
('FBA-09','BioMar Group. Global Sustainability Report 2024.','BioMar Global Sustainability Report 2024','BioMar Group','2025','https://www.biomar.com/media/vrbj10qk/biomar-global-sustainability-report-2024.pdf','','company','2030 target 50% circular and restorative ingredients; 27.4% in 2024; five factories ASC Feed certified in 2024; Vietnam factory run with Viet-Uc; DKK 36 million goodwill write-down in Vietnam in 2023.'),
('FBA-10','BioMar. Sustainability web page. Accessed 25 September 2026.','BioMar sustainability','BioMar Group','2026','https://www.biomar.com/sustainability','','company','States BioMar Viet Uc achieved ASC Feed Certification, the first ASC-certified BioMar facility in Asia.'),
('FBA-11','Charoen Pokphand Foods. Sustainability Report 2025.','CPF Sustainability Report 2025','Charoen Pokphand Foods PCL','2026','https://sustainability.cpfworldwide.com/en/document/viewer/200/sustainability-report-2025','','company','43% of feed corn, soy, palm oil and cassava from deforestation-free, traceable sources against a 100% target; soy for poultry feed deforestation-free since January 2026; probiotic feed; no single-cell or microbial protein found by text search.'),
('FBA-12','De Heus Animal Nutrition. Nourishing Future Generations: Sustainability report 2025.','GL 2025 Nourishing Future Generations, CSR report','Royal De Heus','2025','https://view.publitas.com/de-heus-p6_j7md4b7_b/gl-2025-nourishing-future-generations-csr-report','','company','PDF downloaded from the viewer. Deforestation-free soy and palm on mass balance; strategic dependency risk on soy and feed additives from US, Brazil, Argentina, China; new shrimp feed mill and marine R&D facility at Vinh Long (2024); no novel or microbial ingredient content found.'),
('FBA-13','Grobest. Sustainability Report 2024 (released 30 March 2026).','Grobest Sustainability Report 2024','Grobest Group','2026-03-30','https://www.grobest.com/ridea/images/frontend/pc/tw/Grobest-Sustainability-2024-Report.pdf','','company','Evaluated bacterial SCP and fermented corn protein; 2024 canola protein concentrate trial (up to 80% fishmeal replaced, Taiwan); certified fishmeal 55%, soy 38% (2024); BAP plants 6; GLOBALG.A.P. and ASC at Bien Hoa; functional feeds and EHP trials in Vietnam; claims market leadership in Vietnam.'),
('FBA-14','Tongwei Co. 2025 Environmental, Social and Governance Report and Sustainability Report (Chinese). May 2026.','2025 环境、社会与公司治理报告暨可持续发展报告','Tongwei Co., Ltd.','2026-05','https://www.tongwei.cn/uploads/20260506/964ef4f4115893444d26f2d5593fa5b5.pdf','','company','Feed capacity about 13 Mt a year; microalgae R&D on protein substitution; no single-cell, microbial or yeast protein, fishmeal or soybean-meal terms found by Chinese-language text search.'),
('FBA-15','Vinh Hoan Corporation. Reviewed interim consolidated financial statements for the six months ended 30 June 2026 (English).','VHC reviewed consolidated FS 6M2026','Vinh Hoan Corporation','2026-08','https://www.vinhhoan.com/wp-content/uploads/2026/08/VHC_Reviewed-Consolidated-FS_6M2026_EN.pdf','','company','Note 1: Feed One Joint Stock Company (75% owned), manufacturing livestock and aquatic feeds, My Hiep, Dong Thap; converted to JSC on 26 Jun 2026.'),
('FBA-16','Cargill Vietnam. Company website. Accessed 25 September 2026.','Cargill Viet Nam','Cargill Vietnam','2026','https://www.cargill.com.vn/','','company','Lists livestock, poultry and aquatic feed, supplements and additives; about 1,100 employees; no ingredient strategy. Cargill global aqua sustainability URL returned 404.'),
('FBA-17','UN Comtrade public API. Partner-reported exports to Viet Nam of HS 210220 (inactive yeasts; other dead single-cell micro-organisms), annual 2019 to 2025, all modes, by reporter. Queried 25 September 2026.','Mirror imports of HS 210220 into Viet Nam','United Nations Statistics Division','2026-09-25',CT+'A/HS?period=2025&cmdCode=210220&flowCode=X&partnerCode=704&motCode=0&customsCode=C00&partner2Code=0','','database','Periods 2019 to 2025 queried one by one; saved as raw/mirror_210220_YYYY.json. Net weights reported (not estimated) for main partners. 2025 incomplete (Cambodia and others not yet reported).'),
('FBA-18','UN Comtrade public API. Viet Nam-reported imports of HS 2102 (210210, 210220, 210230), annual 2019 to 2023, and 210220 by partner 2023. Queried 25 September 2026.','Viet Nam imports of HS 2102','United Nations Statistics Division','2026-09-25',CT+'A/HS?reporterCode=704&period=2023&cmdCode=210210,210220,210230&flowCode=M&partnerCode=0&motCode=0&customsCode=C00','','database','Values usable; net weights flagged as estimated (same unit value for every partner). 2024 not available at HS6. Saved as raw/vn_2102_M_YYYY.json.'),
('FBA-19','UN Comtrade public API. Partner-reported imports from Viet Nam of HS 210220, 2024 and 2025. Queried 25 September 2026.','Mirror exports of HS 210220 from Viet Nam','United Nations Statistics Division','2026-09-25',CT+'A/HS?period=2025&cmdCode=210220&flowCode=M&partnerCode=704&motCode=0&customsCode=C00&partner2Code=0','','database','2024: USD 9.84 million, 7,297 t; 2025: USD 11.37 million, 8,166 t (United States, Japan, Canada, Singapore, Thailand).'),
('FBA-20','UN Comtrade public API. Partner-reported exports to Viet Nam of HS 230120 (fishmeal), annual 2024 and 2025 and monthly January to August 2026. Queried 25 September 2026.','Mirror imports of fishmeal into Viet Nam','United Nations Statistics Division','2026-09-25',CT+'M/HS?period=202605&cmdCode=230120&flowCode=X&partnerCode=704&motCode=0&customsCode=C00&partner2Code=0','','database','Annual endpoint /C/A/ for 2024 and 2025; monthly /C/M/ one period per call. 2025 lacks Peru, Ecuador, Senegal and Mauritius; monthly 2026 covers 6 to 10 reporters. Saved as raw/mirror_230120_YYYY.json and raw/fm_YYYYMM.json.'),
('FBA-21','Phileo by Lesaffre. Aquaculture web page. Accessed 25 September 2026.','Phileo aquaculture solutions','Phileo by Lesaffre','2026','https://phileo-lesaffre.com/en/aquaculture/','','company','Yeast probiotic (Actisaf), yeast fractions (Safglucan, Safmannan, Nucleosaf), selenium yeast and Prosaf for shrimp and fish; no doses or Vietnam trials on the page.'),
('FBA-22','OpenAlex. Query: works 2019 to 2026 with a Viet Nam-affiliated author whose title or abstract combines shrimp, whiteleg shrimp, pangasius or striped catfish with single-cell protein, yeast, yeast culture, bacterial meal, microbial protein or beta-glucan. Run 25 September 2026.','OpenAlex query, Vietnam microbial feed trials','OpenAlex','2026-09-25','https://api.openalex.org/?oql=works%20where%20institution%20country%20is%20(VN)%20and%20retracted%20is%20(false)%20and%20year%20%3E%20(2018)%20and%20title%2Fabstract%20has%20(%20(%20stemmed%20%22Litopenaeus%20vannamei%22%20or%20stemmed%20%22Penaeus%20vannamei%22%20or%20stemmed%20%22striped%20catfish%22%20or%20pangasius%20or%20shrimp%20)%20and%20(%20stemmed%20%22bacterial%20meal%22%20or%20stemmed%20%22beta-glucan%22%20or%20stemmed%20%22microbial%20protein%22%20or%20stemmed%20%22single%20cell%20protein%22%20or%20stemmed%20%22yeast%20culture%22%20or%20stemmed%20%22yeast%22%20)%20)','','database','11 results; none a feed-mill or company trial of microbial protein in shrimp or pangasius; one industry-linked functional yeast product trial (Novriadi et al. 2022, Indonesia journal).'),
('FBA-23','Minh Phu Seafood Corporation. Company home page. Accessed 25 September 2026.','Minh Phu Seafood','Minh Phu Seafood Corporation','2026','https://www.minhphu.com/','','company','No feed, certification or ingredient information on the page.'),
('FBA-24','BioMar Group. Interim Report for Q2 2026 (first half 2026).','BioMar Group first half 2026 interim report','BioMar Group','2026-08','https://www.biomar.com/media/jbja42gf/biomar-group-first-half-2026-interim-report.pdf','','company','H1 2026 feed volumes up 5%, driven by shrimp feed in Ecuador and ramp-up volume in Vietnam.'),
]
with open('sources.csv','w',newline='',encoding='utf-8') as f:
    w=csv.writer(f); w.writerow(['source_id','citation','title','author_or_publisher','date','url','doi','source_type','accessed','notes'])
    for s in S: w.writerow([s[0],s[1],s[2],s[3],s[4],s[5],s[6],s[7],A,s[8]])
s=open('sources.csv',encoding='utf-8').read(); assert chr(0x2013) not in s and chr(0x2014) not in s
print(len(S))
